print("Hello, world!")
name = input("Input your name - ")
print(name)
age = input("Input your age - ")
print(age)
a = int(input("Enter integer value a -"))
b = int(input("Enter integer value b -"))
print(a + b)
print(a / b)
print(a == b)
print(a % b)
print(a - b)
